- name: Unziping OpenAM
  shell: unzip -o -j /vagrant/AM-eval-5.1.0.zip -d /tmp/openam

- name: Move OpenAM war file to Tomcat webapp folder
  shell: mv /tmp/openam/AM-eval-5.1.0.war /usr/share/tomcat/webapps/openam.war

- name: Restarting Tomcat
  service:
    name: tomcat
    state: restarted

- name: "wait for OpenAM to come up"
  uri:
    url: "http://127.0.0.1:8080/openam/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
